#pragma once

enum TileType
{
	TILE_NONE = 0,
	TILE_DIRT,
	TILE_GRASS,
	TILE_FOREST,
	TILE_COUNT
};

enum TileID
{
	TILEID_NONE = 0,

	TILEID_DIRT_00 = 1,
	TILEID_DIRT_01 = 2,
	TILEID_DIRT_02 = 3,
	TILEID_DIRT_03 = 4,

	TILEID_GRASS_00 = 101,
	TILEID_GRASS_01 = 102,
	TILEID_GRASS_02 = 103,
	TILEID_GRASS_03 = 104,

	TILEID_FOREST_00 = 201,
	TILEID_FOREST_01 = 202,
	TILEID_FOREST_02 = 203,
	TILEID_FOREST_03 = 204,

};

// 씬 타입 정의
enum SceneType
{
	SCENE_NONE = 0,
	SCENE_TITLE,               // 타이틀 씬
	SCENE_CHARACTER_SELECT,    // 캐릭터 선택 씬
	SCENE_GAME_FARMING_AREA,        // 1번째: 농장 지역
	SCENE_GAME_HOUND_FOREST,        // 2번째: 하운드 숲
	SCENE_GAME_SPIDER_QUEEN_HOUSE,  // 3번째: 거미여왕 집
	SCENE_COUNT
};

enum GameObjectID : UINT {
	GOID_NONE = 0,

	// 자연 오브젝트 (1 ~ 99)
	GOID_NORMAL_GRASS = 1,
	GOID_NORMAL_TREE_SHORT = 2,
	GOID_NORMAL_TREE_NORMAL = 3,
	GOID_NORMAL_TREE_TALL = 4,
	GOID_NORMAL_ROCK = 5,
	GOID_GOLD_ROCK = 6,
	GOID_NORMAL_SAPLING = 7,
	GOID_BERRY_TREE = 8,

	// 몬스터 (100 ~ 199)
	GOID_MONSTER_PIG = 101,
	GOID_MONSTER_SPIDER = 102,
	GOID_MONSTER_WARRIOR_SPIDER = 103,
	GOID_MONSTER_QUEEN_SPIDER = 104,
	GOID_MONSTER_HOUNDDOG = 105,
	GOID_MONSTER_REDHOUNDDOG = 106,
	GOID_MONSTER_ICEHOUNDDOG = 107,

	// 건물들 (200 ~ 299)
	GOID_BUILDING_PIGHOUSE = 201,
	GOID_BUILDING_SPIDER_SMALLEGG = 202,
	GOID_BUILDING_SPIDER_NORMALEGG = 203,
	GOID_BUILDING_SPIDER_TALLEGG = 204,
	GOID_BUILDING_SPIDER_SACEGG = 205,

	// 아이템 - 재료 (300 ~ 399)
	GOID_ITEM_CUT_NORMAL_GRASS = 301,
	GOID_ITEM_NORMAL_TREE_LOG = 302,
	GOID_ITEM_NORMAL_TWIGS = 303,
	GOID_ITEM_NORMAL_ROCK = 304,
	GOID_ITEM_GOLD_ROCK = 305,
	GOID_ITEM_ROPE = 306,
	GOID_ITEM_CUT_NORMAL_STONE = 307,
	GOID_ITEM_MEAT = 308,
	GOID_ITEM_BERRY = 309,
	GOID_ITEM_WOOD_2 = 310,
	GOID_ITEM_SMALL_MEAT = 311,
	GOID_ITEM_MONSTER_MEAT = 312,
	GOID_ITEM_COOKED_MONSTER_MEAT = 313,
	GOID_ITEM_COOKED_SMALL_MEAT = 314,
	GOID_ITEM_COOKED_MEAT = 315,

	// 도구 - 장비 (400 ~ 499)
	GOID_TOOL_GOLDEN_SCYTHE = 401,
	GOID_TOOL_HAM_BAT = 402,
	GOID_TOOL_PICKAXE = 403,
	GOID_TOOL_RED_AXE = 404,
	GOID_TOOL_SPEAR = 405,
	GOID_TOOL_SWAP_AXE = 406,
	GOID_TOOL_SWAP_SPEAR = 407,
	GOID_TOOL_TORCH = 408,
	GOID_TOOL_HALBERD = 409,
	GOID_TOOL_HAMMER = 410,

	// 플레이어 캐릭터 (1000 ~ 1999)
	GOID_PLAYER_WILSON = 1001,
	GOID_PLAYER_WILLOW = 1002,
	GOID_PLAYER_WOLFGANG = 1003,

	// UI (3000 ~ )
	GOID_MAIN_BG = 3001,
	GOID_GAME_LOGO = 3002,
	GOID_BUTTON1 = 3003,
	GOID_ENDBUTTON1 = 3004,
	GOID_SELECT_BUTTON = 3005,
	GOID_CANCEL_SELECTION = 3006,
	GOID_BACK_BUTTON = 3007,
	GOID_PLAYER_PORTRAIT = 3008,
	GOID_PLAYER_INFO = 3009,
	GOID_CHARACTER_DESCRIPTION = 3010,
	GOID_BUTTON1_TEXT = 3011,
	GOID_ENDBUTTON1_TEXT = 3012,
	GOID_SELECT_BUTTON_TEXT = 3013,
	GOID_CANCEL_SELECTION_TEXT = 3014,
	GOID_BACK_BUTTON_TEXT = 3015,
	GOID_CRAFT_BAR = 3016,
	GOID_CRAFT_ICON = 3017,
	GOID_CRAFT_TOOL_GOLDEN_SCYTHE = 3018,
	GOID_CRAFT_TOOL_HAM_BAT = 3019,
	GOID_CRAFT_TOOL_PICKAXE = 3020,
	GOID_CRAFT_TOOL_RED_AXE = 3021,
	GOID_CRAFT_TOOL_SPEAR = 3022,
	GOID_CRAFT_TOOL_SWAP_AXE = 3023,
	GOID_CRAFT_TOOL_SWAP_SPEAR = 3024,
	GOID_CRAFT_TOOL_TORCH = 3025,
	GOID_CRAFT_TOOL_HALBERD = 3026,
	GOID_CRAFT_TOOL_HAMMER = 3027,
};

// GameObject 방향 정의 (전역 유지)
enum Direction {
	DIR_NONE = 0,
	DIR_UP,
	DIR_DOWN,
	DIR_LEFT,
	DIR_RIGHT,
	DIR_COUNT
};

enum RenderLayer {
	LAYER_NONE = -1,
	LAYER_TILE_BACKGROUND = 0,   // 타일 (배경 아래)
	LAYER_WORLD_TILE,
	LAYER_WORLD_OBJECT,          // 월드 오브젝트 (맵 위 오브젝트)
	LAYER_UI_BACKGROUND,         // UI 배경
	LAYER_UI_FOREGROUND,         // UI 요소들, 텍스트
	LAYER_DEBUG_OVERLAY,         // 디버그 오버레이 (최상 위)

	LAYER_COUNT                  // 레이어 개수
};

enum Time {
	NOON = 0,
	NIGHT,
	TIME_COUNT
};

// 렌더링 명령 종류
enum DrawCommandType {
	DRAW_COMMAND_IMAGE,
	DRAW_COMMAND_TEXT,
	DRAW_COMMAND_RECTANGLE,
	DRAW_COMMAND_FILL_RECTANGLE,
	DRAW_COMMAND_ELLIPSE
};

// 콜라이더 타입 정의
enum ColliderType {
	COLLIDER_BOX = 0,      // 사각형 콜라이더
	COLLIDER_CIRCLE,       // 원형 콜라이더
	COLLIDER_COUNT
};